### ISSUE TITLE
How to add localization to beatsaber?

### ISSUE THREAD

**Issue by cgapk123** [sc2ad/QuestModdingTools#1]
The easiest way

**Comment by sc2ad** [comment]
Hello! Glad you are interested, however, this repo is currently significantly outdated. If you are interested in replacing english text in game (for the Oculus Quest) you should check out my other repository located here: https://github.com/sc2ad/QuestSaberPatch/tree/master using the jsonApp2. However, there does not yet currently exist a way to replace other languages besides english. It shouldn't be too difficult, but I haven't gotten around to it yet. I'll look at it tonight, if that is what you are looking for.

Please message me on Discord: Sc2ad#8836 to follow up on this more concisely.

**Comment by sc2ad** [comment]
I added a commit to the latest version of this repo: https://github.com/sc2ad/QuestSaberPatch/tree/master which should have multiple language support, when using the advanced json interface as described in the README of that repo. Feel free to ask me any follow up questions, I'll be closing this issue unless you have some more concerns.
